# -*- encoding: utf-8 -*-

=begin
#CyberSource Flex API

#Simple PAN tokenization service

OpenAPI spec version: 0.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

$:.push File.expand_path("../lib", __FILE__)
require "cybersource_rest_client/version"

Gem::Specification.new do |s|
  s.name        = "cybersource_rest_client"
  s.version     = "0.0.85"
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["CyberSource"]
  s.email       = ["cybersourcedev@gmail.com"]
  s.homepage    = "https://developer.cybersource.com"
  s.summary     = "CyberSource Ruby SDK Gem"
  s.description = "Simple REST API for the CyberSource Global Payments Platform"
  s.license     = "CyberSource"
  s.files       = Dir.glob("{lib}/{cybersource_rest_client}/**/*") + Dir.glob("{lib}/{AuthenticationSDK}/authentication/**/*") + Dir.glob("{lib}/{AuthenticationSDK}/core/**/*") + Dir.glob("{lib}/{AuthenticationSDK}/util/**/*") + Dir.glob("{lib}/{AuthenticationSDK}/logging/**/*") + Dir.glob("{lib}/cybersource_rest_client.rb")
  s.required_ruby_version = ">= 3.1"

  s.add_runtime_dependency 'typhoeus', '~> 1.5','>=1.5.0'
  s.add_runtime_dependency 'json', '~>2.18', '>= 2.18.1'
  # goco-inc fork: relaxed from '~> 7.2' — goco-api runs Rails 7.1; the SDK only
  # uses ActiveSupport::Cache::MemoryStore, available well before 7.2.
  s.add_runtime_dependency 'activesupport', '>= 7.1'
  s.add_runtime_dependency 'interface','~> 1.0', '>= 1.0.5'
  # goco-inc fork: relaxed from '~> 3.1' — goco-api is capped at jwt <3 by other
  # gems; the SDK's shared-secret/JWT paths use only stable HS256/RS256 APIs that
  # work on jwt 2.7+. (::JWT::Base64 etc. are in capture_context, not the report path.)
  s.add_runtime_dependency 'jwt', '>= 2.7'
  s.add_runtime_dependency 'addressable', '~> 2.8', '>= 2.8.8'
  s.add_runtime_dependency 'time', '~>0.4.2'
  s.add_runtime_dependency 'jose', '~> 1.2'

  s.add_development_dependency 'rubocop', '>=1.31.0','<1.31.1'
  s.add_development_dependency 'rspec', '~> 3.13', '>= 3.13.2'
  s.add_development_dependency 'vcr', '~> 6.4.0'
  s.add_development_dependency 'autotest', '~> 5.0', '>= 5.0.0'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-fsevent', '~> 0.3.1', '>= 0.3.1'
  
  s.require_paths = ["lib"]
end
