
asset_id: 5699322921771307554
asset_alias: Intuit.work.payroll.cybersourceruby

mavenSettingsFileId: ibp-maven-settings-file
artifactoryCredentialsId: artifactory-cybersource-ruby
mavenImage: "oicp/standard/maven/amzn-maven-corretto11:5"
MAIN_BRANCH: "master"
groupId: com.intuit.work-payroll.cybersource-ruby
artifactId: cybersource-ruby
jacocoExecPattern: "target/*.exec"

githubCredentialsId: "github-svc-sbseg-ci"
orgRepo: work-payroll/cybersource-ruby

CODECOV_CREDENTIALS: ibp-codecov-token
SONAR_HOST: https://sonarqube.tools-k8s.a.intuit.com/
GITHUB_API: https://github.intuit.com/api/v3/

enableJiraTransition: false
